version: '2'
services:
  app-lb1:
    image: rancher/lb-service-haproxy:v0.9.14
    ports:
    - ${app_lb_port}:${app_lb_port}
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  app-db-lb1:
    image: rancher/lb-service-haproxy:v0.9.14
    expose:
    - ${mysql_lb_port}:${mysql_lb_port}
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  joomla:
    image: joomla
    hostname: joomla
    environment:
      JOOMLA_DB_PASSWORD: ${joomla_db_password}
      JOOMLA_DB_USER: ${joomla_db_user}
      JOOMLA_DB_HOST: ${joomla_db_host}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_ROOT_PASSWORD: ${mysql_random_root_password}
      MYSQL_PASSWORD: ${mysql_password}
    stdin_open: true
    volumes:
    - mysql-vol:/var/lib/mysql/data
    tty: true
    labels:
      io.rancher.container.pull_image: always

